---
version: '3.8'
services:
  spc:
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - spc-net
    ports:
      - 8080:8080
    depends_on:
      - spc-db
  spc-db:
    image: mysql:8
    networks:
      - spc-net
    ports:
      - 3306
    volumes:
      - spc-vol:/var/lib/ysql
    environment:
      - MYSQL_ROOT_PASSWORD=nop123
      - MYSQL_DATABASE=nop
      - MYSQL_USER=nop
      - MYSQL_PASSWORD=nop123
    

networks:
  spc-net:
    ipam:
      driver: default
      config:
        - subnet: 10.100.0.0/16

volumes:
  spc-vol: