FROM alpine:3 AS downloader
ADD https://github.com/nopSolutions/nopCommerce/releases/download/release-4.60.6/nopCommerce_4.60.6_NoSource_linux_x64.zip /nop/nopCommerce_4.60.6_NoSource_linux_x64.zip
RUN apk update && apk add unzip && cd nop && unzip nopCommerce_4.60.6_NoSource_linux_x64.zip && mkdir bin logs && rm nopCommerce_4.60.6_NoSource_linux_x64.zip

FROM mcr.microsoft.com/dotnet/sdk:7.0
LABEL Author="Ashfaq" project="nop"
ENV ASPNETCORE_URLS="http://0.0.0.0:5000"
WORKDIR /nopcommerce
COPY --from=downloader /nop /nopcommerce
EXPOSE 5000
CMD ["dotnet","Nop.Web.dll"]