---
version: '3.8'
services:
  gol:
    build: .
    networks:
      gol-net:
    ports:
      - 8080:8080

networks:
  gol-net:
    ipam:
      driver: default
      config:
        - subnet: 10.100.0.0/24