FROM maven:3-amazoncorretto-17 AS builder
COPY . /spc
RUN cd /spc && mvn package

FROM amazoncorretto:17-alpine3.16
LABEL author="Ashfaque" project="spc"
ARG USERNAME='spc'
ARG WORKDIR='/spc'
COPY --from=builder --chown=${USERNAME}:${USERNAME} /spc/target/spring-petclinic-*.jar  ${WORKDIR}/spring-petclinic-*.jar
RUN adduser -h ${USERNAME} -s /bin/sh -D ${USERNAME}
USER ${USERNAME}
WORKDIR ${WORKDIR}
EXPOSE 8080
CMD [ "java", "-jar","spring-petclinic-*.jar" ]